version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: elev8_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/tmp
      - /app/log
      - /app/.git
      - /app/public/packs
      - /app/public/assets
      - bundle_cache:/usr/local/bundle
      
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.development

  test:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rspec"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    env_file:
      - .env.test

volumes:
  bundle_cache:
  postgres_data:
